[versions]
micronaut = "3.6.0"
micronaut-docs = "2.0.0"
groovy = "3.0.12"

glassfish-el = '2.2.1-b05'
glassfish-javax-el = '3.0.1-b12'
hibernate-validator = '8.0.0.Final'

[libraries]
glassfish-el = { module = 'org.glassfish.web:el-impl', version.ref = 'glassfish-el' }
glassfish-javax-el = { module = 'org.glassfish:javax.el', version.ref = 'glassfish-javax-el' }
hibernate-validator = { module = 'org.hibernate:hibernate-validator', version.ref = 'hibernate-validator' }
