[versions]
managed-hibernate-validator = '8.0.1.Final'

groovy = "4.0.18"

micronaut = "4.3.9"
micronaut-docs = "2.0.0"
micronaut-serde = "2.8.1"
micronaut-test = "4.2.1"
micronaut-validation = "4.4.0"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

# BOMs
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }
hibernate-validator = { module = 'org.hibernate:hibernate-validator', version.ref = 'managed-hibernate-validator' }
